# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'admin_mode.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(781, 354)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 30, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.newPasswordEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.newPasswordEdit.setGeometry(QtCore.QRect(270, 10, 211, 31))
        self.newPasswordEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.newPasswordEdit.setObjectName("newPasswordEdit")
        self.confirmPasswordEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.confirmPasswordEdit.setEnabled(True)
        self.confirmPasswordEdit.setGeometry(QtCore.QRect(270, 70, 211, 31))
        self.confirmPasswordEdit.setInputMask("")
        self.confirmPasswordEdit.setText("")
        self.confirmPasswordEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.confirmPasswordEdit.setObjectName("confirmPasswordEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.changeUserPermButton = QtWidgets.QPushButton(self.centralwidget)
        self.changeUserPermButton.setGeometry(QtCore.QRect(290, 240, 121, 41))
        self.changeUserPermButton.setObjectName("changeUserPermButton")
        self.changePasswordButton = QtWidgets.QPushButton(self.centralwidget)
        self.changePasswordButton.setGeometry(QtCore.QRect(520, 30, 121, 41))
        self.changePasswordButton.setObjectName("changePasswordButton")
        self.blockCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.blockCheckBox.setGeometry(QtCore.QRect(300, 160, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.blockCheckBox.setFont(font)
        self.blockCheckBox.setObjectName("blockCheckBox")
        self.extraPasswordCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.extraPasswordCheckBox.setGeometry(QtCore.QRect(300, 200, 211, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.extraPasswordCheckBox.setFont(font)
        self.extraPasswordCheckBox.setObjectName("extraPasswordCheckBox")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(30, 120, 256, 192))
        self.listWidget.setObjectName("listWidget")
        self.addUserButton = QtWidgets.QPushButton(self.centralwidget)
        self.addUserButton.setGeometry(QtCore.QRect(550, 230, 91, 41))
        self.addUserButton.setObjectName("addUserButton")
        self.userLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.userLineEdit.setGeometry(QtCore.QRect(530, 200, 151, 21))
        self.userLineEdit.setObjectName("userLineEdit")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(530, 160, 211, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.errorPasswordLabel = QtWidgets.QLabel(self.centralwidget)
        self.errorPasswordLabel.setGeometry(QtCore.QRect(240, 50, 271, 20))
        self.errorPasswordLabel.setText("")
        self.errorPasswordLabel.setObjectName("errorPasswordLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 781, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Режим администратора"))
        self.label.setText(_translate("MainWindow", "Новый пароль"))
        self.label_2.setText(_translate("MainWindow", "Подтверждение"))
        self.changeUserPermButton.setText(_translate("MainWindow", "Применить"))
        self.changePasswordButton.setText(_translate("MainWindow", "Сменить пароль"))
        self.blockCheckBox.setText(_translate("MainWindow", "Блокировка"))
        self.extraPasswordCheckBox.setText(_translate("MainWindow", "Ограничение на пароль"))
        self.addUserButton.setText(_translate("MainWindow", "Добавить"))
        self.label_3.setText(_translate("MainWindow", "Новый пользователь"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
